### ISSUE TITLE
Button introduction open new tab

### ISSUE THREAD

**Issue by renatosuero** [renatosuero/vimschool#16]
In the home, the button **introduction** open new tab. 
<img width="224" alt="screen shot 2018-02-03 at 13 37 22" src="https://user-images.githubusercontent.com/1093214/35767603-7198f4ae-08e7-11e8-87e7-8e1803e2f487.png">

That is the only place that has a button to navigate into the pages. I think that we should remove it or add in other pages, but we have the arrows **<** **>** to navigate. I don't know, @rgerardi what do you think about this?

**Comment by rgerardi** [comment]
I agree. I think this button is not required. I will remove it.
